// <auto-generated />
using BlokjeKwijt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlokjeKwijt.Data.Migrations
{
    [DbContext(typeof(BlokjeKwijtContext))]
    [Migration("20211207135735_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlokjeKwijt.Data.Aanvraag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bericht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoonNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aanvragen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bericht = "Ik zou graag een groen blokje aan willen vragen met 6 nopjes",
                            Email = "ray@home.nl",
                            Naam = "Ray",
                            TelefoonNummer = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            Bericht = "Ik zou graag een roze blokje willen aanvragen met 12 nopjes",
                            Email = "gijs@home.nl",
                            Naam = "Gijs",
                            TelefoonNummer = "0615935712"
                        },
                        new
                        {
                            Id = 3,
                            Bericht = "Ik zou graag een oranje blokje aan willen vragen met 14 nopjes",
                            Email = "nick@home.nl",
                            Naam = "Nick",
                            TelefoonNummer = "0687654321"
                        });
                });

            modelBuilder.Entity("BlokjeKwijt.Data.Blokje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlokNummer")
                        .HasColumnType("int");

                    b.Property<int>("Breedte")
                        .HasColumnType("int");

                    b.Property<int>("Hoogte")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KleurId")
                        .HasColumnType("int");

                    b.Property<int>("Lengte")
                        .HasColumnType("int");

                    b.Property<int>("Nopjes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KleurId");

                    b.ToTable("Blokjes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlokNummer = 10,
                            Breedte = 5,
                            Hoogte = 1,
                            ImageName = "Rood.jpg",
                            KleurId = 1,
                            Lengte = 10,
                            Nopjes = 50
                        },
                        new
                        {
                            Id = 2,
                            BlokNummer = 5,
                            Breedte = 2,
                            Hoogte = 2,
                            ImageName = "Geel.jpg",
                            KleurId = 2,
                            Lengte = 4,
                            Nopjes = 20
                        },
                        new
                        {
                            Id = 3,
                            BlokNummer = 8,
                            Breedte = 5,
                            Hoogte = 0,
                            ImageName = "Blauw.jpg",
                            KleurId = 3,
                            Lengte = 4,
                            Nopjes = 32
                        });
                });

            modelBuilder.Entity("BlokjeKwijt.Data.BlokjesVerzoek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlokjeId")
                        .HasColumnType("int");

                    b.Property<int>("BlokjeOverKwijt")
                        .HasColumnType("int");

                    b.Property<int>("BlokjesVerzoekStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BlokjesVerzoeken");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlokjeId = 1,
                            BlokjeOverKwijt = 1,
                            BlokjesVerzoekStatus = 1
                        },
                        new
                        {
                            Id = 2,
                            BlokjeId = 1,
                            BlokjeOverKwijt = 0,
                            BlokjesVerzoekStatus = 1
                        });
                });

            modelBuilder.Entity("BlokjeKwijt.Data.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoonNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ray@home.nl",
                            Naam = "Ray",
                            TelefoonNummer = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "gijs@home.nl",
                            Naam = "Gijs",
                            TelefoonNummer = "0615935712"
                        },
                        new
                        {
                            Id = 3,
                            Email = "nick@home.nl",
                            Naam = "Nick",
                            TelefoonNummer = "0687654321"
                        });
                });

            modelBuilder.Entity("BlokjeKwijt.Data.Kleur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KleurCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KleurNaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kleuren");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KleurCode = "#ff0000",
                            KleurNaam = "Rood"
                        },
                        new
                        {
                            Id = 2,
                            KleurCode = "##FFFF00",
                            KleurNaam = "Geel"
                        },
                        new
                        {
                            Id = 3,
                            KleurCode = "#0000FF",
                            KleurNaam = "Blauw"
                        });
                });

            modelBuilder.Entity("BlokjeKwijt.Data.Blokje", b =>
                {
                    b.HasOne("BlokjeKwijt.Data.Kleur", "KleurBlokje")
                        .WithMany()
                        .HasForeignKey("KleurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KleurBlokje");
                });
#pragma warning restore 612, 618
        }
    }
}
